[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist" # <-- or your build output folder (e.g., build, out, etc.)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200